export const environment = {
  host: 'http://localhost:8080/',
  register:'user/register',
  getUserInfoByUsername:'user/get-user-username-',
  getUserInfo:'get-user-info-',
  deleteUser: 'delete-user-',
  editUser:'edit-user',
  updateUserWeight:'weight-history-user-',
  changePassword:'change-password',
  addWorkout:'add-workout',
  getWorkoutById:'get-workout-',
  getWorkoutByUserId:'get-workouts-by-userid-',
  editWorkout:'edit-workout',
  deleteWorkout:'delete-workout-',
  addExercise:'add-exercise',
  getExerciseById:'get-exercise-',
  getAllExercises:'get-all-exercises/',
  getExercisesByCategory:'get-exercises-by-',
  deleteExerciseById:'delete-exercise-',
  editExercise:'edit-exercise',
  addFoodItem:'add-food-item',
  editFoodItem:'edit-food-item',
  deleteFoodItem:'delete-food-item-',
  getFoodItemById:'get-food-item-',
  getAllFoodItems:'get-food-items',
};
